### ISSUE TITLE
Epic: Sites to Scrape From

### ISSUE THREAD

**Issue by Ezequiel-Valencia** [AvocadoMoon/CTEventScraper#1]
### Problem
There are sites which publish local events on them, but we want them to centralized in one location for easy search and pooled into a DB of other events people publish.

### Solution
Create a web scraper that is able to gather all the information desired in a digestible form, and a driver which then publishes these events onto a website.

#### Driver Tasks

- [x] Create a driver that is compatible with the Mobilizon API

#### Scraper Tasks

- [ ] Create some interface that the scrapers must oblige to
- [ ] Scrape for the following sites:
    - [ ] Cafe9
    - [ ] Howard's Book Store
    - [ ] Toad's Place
    - [ ] [Best Video Film & Cultural Center](https://www.bestvideo.com/)
    - [ ] Music Haven
    - [ ] Park City Music Hall
    - [ ] Black rock books
    - [ ] [Yoga City](https://yogainourcity.com/)
    - [ ] [New Haven Cat Cafe](https://mewhavencatcafe.com/book.html)
    - [ ] [Jazz Haven](https://jazzhaven.org/events/)
    - [ ] [Space Ballroom](https://spaceballroom.com/calendar/)
    - [ ] [Stella Blues](https://www.stellabluesbar.com/calendar)
    - [ ] [Siera Club](https://vault.sierraclub.org/online-activities/iframe-entity.aspx?e=chapter/3900&v=list&mt=hybrid)
- [ ] Google calendar supported sites
    - [x] [Hartford Jazz Society](https://hartfordjazzsociety.com/events/)
    - [x] [WBT](https://www.witchbitchthrift.com/pages/events)
    - [x] [Elm City Games](https://www.elmcitygames.com/calendar)
    - [x] [Downtown New Haven](https://www.downtownnewhaven.com/nhv-events)
    - [x] [Bradely Street Bike-Coop](https://bsbc.co/events)
    - [x] [Healing Meals](https://healingmealsproject.org/)
    - [x] [Save the sound](https://www.savethesound.org/take-action/upcoming-events/)
    - [x] [New Haven Library](https://nhfpl.libnet.info/events)
    - [x] [Hartford Public Library](https://programs.hplct.org/events)
    - [ ] [Koffee](https://www.koffeefamily.com/koffee-afterdark)

**Comment by AvocadoMoon** [comment]
[Scraper for Microformats following schema.org](https://scrapfly.io/blog/web-scraping-microformats/)

**Comment by AvocadoMoon** [comment]
Looks like some of the sites use word press which has some API that may be applicable for tapping into. Also there seems to be a library within python that is used for calendars, and my be able to pull online calendars.

**Comment by AvocadoMoon** [comment]
Jazz haven has a subscribe method which features [ICAL](https://jazzhaven.org/events/?ical=1&tribe_display=month)
